baseURL = "https://maximousblk.now.sh/"
title = "Maximous Black"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsStyle = "dracula"
paginate = 10
copyright = 'This work is licensed under the Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International license'
googleAnalytics = "UA-131672698-1"

# disqusShortname = ""
[permalinks]
posts = "/post/:title/"

[author]
name = "Maximous Black"

[blackfriday]
hrefTargetBlank = true

[taxonomies]
tag = "tags"
category = "categories"
series = "series"

[params]
# Metadata mostly used in document's head
description = "I'm a Web Developer who likes building beautiful web interfaces & experiences."
images = ["og_home.jpg"]
keywords = "maximous, black, web, developer, software, engneer, javascript, design"
homeSubtitle = "I'm a Web Developer who likes building beautiful web interfaces & experiences."
og_image = "og_home.jpg"
preconnect = ["https://rsms.me/", "https://cdn.maximousblk.now.sh/"]
defaultTheme = "light" # "light" or "dark"
handle = "maximousblk"

[params.license]
text = "CC BY-NC-ND 4.0"
link = "https://creativecommons.org/licenses/by-nc-nd/4.0/"

[params.logo]
logoText = "Maximous Black"
logoHomeLink = "/"

[params.portrait]
path = "/logo.png"
alt = "]V["

# Social icons
[[params.social]]
name = "github"
url = "https://github.com/maximousblk"

[[params.social]]
name = "twitter"
url = "https://twitter.com/maximousblk"

[[params.social]]
name = "instagram"
url = "https://instagram.com/maximousblk"

[[params.social]]
name = "keybase"
url = "https://keybase.io/maximousblk"

[[params.social]]
name = "medium"
url = "https://medium.com/@maximousblk"

[[params.social]]
name = "telegram"
url = "https://t.me/maximousblk"

[[params.social]]
name = "dribbble"
url = "https://dribbble.com/maximousblk"

[[params.social]]
name = "email"
url = "mailto:maximousblk@gmail.com"

[menu]

[[menu.main]]
identifier = "about"
name = "About"
url = "about/"

[[menu.main]]
identifier = "posts"
name = "Posts"
url = "posts/"

[[menu.main]]
identifier = "RSS"
name = "RSS"
url = "posts/index.xml"
